# Generated by Django 5.2.17 on 2026-09-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_booking_payment_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster_1',
            new_name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_2',
        ),
    ]
